### ISSUE TITLE
Code coverage badge problem

### ISSUE THREAD

**Issue by allevo** [staticdeploy/staticdeploy#28]
For the time being the code coverage is 0. Why?

![image](https://user-images.githubusercontent.com/1054125/54385850-e8211900-4697-11e9-85d9-521e6d464f21.png)

**Comment by pscanf** [comment]
Ah, should be because of [this bug](https://github.com/yarnpkg/yarn/issues/6746) in `yarn` (or maybe `nyc`). Basically when running `yarn coverage` process pid-s are not passed correctly and that results in `nyc` returning 0% coverage. I should be fixable by changing `yarn coverage` to `npm run coverage` [here](https://github.com/staticdeploy/staticdeploy/blob/master/.circleci/config.yml#L38).

I never bothered to do it, but I'll try now. 🙂

**Comment by pscanf** [comment]
See staticdeploy/staticdeploy#29

**Comment by pscanf** [comment]
Thanks for the heads up! Looks better now 🙂
