### ISSUE TITLE
Is there a performance related test?

### ISSUE THREAD

**Issue by gongchao** [staticdeploy/staticdeploy#39]
Does this project have specific performance tests?

**Comment by pscanf** [comment]
Hello @gongchao. No, at the moment there are no performance tests.

For StaticDeploy though being performant when serving static files is not _that important_. This is because in production / when performance matters, you should use StaticDeploy in combination with a CDN (or any other caching layer, like Varnish), that can do a much better job at optimizing performance. You _could_ horizontally scale StaticDeploy, there's nothing that prevents it, but the caching layer approach I think is just more efficient and effective.

To give you an example, the largest deployment of StaticDeploy I'm working with is serving single page applications to around 50k daily unique users, but of course it's behind a CDN, so a very small fraction of those requests actually hit StaticDeploy. The deployment is also hosting the staging environments of those SPAs, as well as some internal documentation websites. Those are *not* behind a CDN, because only around 40 developers / testers access them, and at this small scale people don't notice any difference in performance. Google Lighthouse would not give you a perfect performance score though. :)

That said, in the future I might consider adding some performance tests to monitor that the baseline performance stays acceptable in various situations (thousands of entrypoints, thousands of bundles, etc).
